#!/usr/bin/env bash
#creating a symbolic link to connect config files while overwriting it if there
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
