#!/usr/bin/env bash

# This script connects to a remote server with IP address 34.207.64.43
# using the ssh command and the ubuntu user, using the private key
# located at ~/.ssh/school.

ssh ubuntu@34.207.64.43 -i ~/.ssh/school
